### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 11087491: invalid start byte

### ISSUE THREAD

**Issue by Manikanth06** [ShiningLab/POS-Tagger-for-Punctuation-Restoration#4]
@MrShininnnnn ,
I am getting below error , how to solve this?

**ERROR:**
Initialize...
2022-06-10 14:19:48,300 loading file C:\Users\Manikanth Shetty\.flair\models\upos-english-fast\b631371788604e95f27b6567fe7220e4a7e8d03201f3d862e6204dbf90f9f164.0afb95b43b32509bf4fcc3687f7c64157d8880d08f813124c1bd371c3d8ee3f7
Traceback (most recent call last):
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 483, in <module>
    main()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 478, in main
    re = Restorer()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 29, in __init__
    self.load_data()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 72, in load_data
    train_dataset = pipeline.Dataset(
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\src\utils\pipeline.py", line 160, in __init__
    self.raw_data = load.load_json(data_file)
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\src\utils\load.py", line 12, in load_json
    return json.load(f)
  File "C:\Users\Manikanth Shetty\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Manikanth Shetty\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 11087491: invalid start byte

**Comment by MrShininnnnn** [comment]
Hi @Manikanth06,

What is the version of your flair now? It should be 0.8. If you make sure that the code is in an independent virtual env with the correct library version, please clean the res folder. It means to delete all the post-generated files. Then, try to run the code again.

The error is due to a failed JSON loading via main\src\utils\load.py for data files. Thus, the problem should be either the JSON loading function or the data files.

**Comment by Manikanth06** [comment]
@MrShininnnnn 
flair version is 0.8 now.

**Comment by Manikanth06** [comment]
@MrShininnnnn ,

**ERROR**
Traceback (most recent call last):
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 483, in <module>
    main()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 478, in main
    re = Restorer()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 29, in __init__
    self.load_data()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\train.py", line 87, in load_data
    valid_dataset = pipeline.Dataset(
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\src\utils\pipeline.py", line 165, in __init__
    self.get_pairs()
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\src\utils\pipeline.py", line 170, in get_pairs
    self.xs, self.ys, self.y_masks, self.y_tags = generate_seqs(self.raw_data, self.config)
  File "c:\Users\Manikanth Shetty\OneDrive\Documents\POS-Tagger-for-Punctuation-Restoration-main\main\src\utils\pipeline.py", line 113, in generate_seqs
    **token, pun, mask, tag = l**
ValueError: not enough values to unpack (expected 4, got 3)

In the code  as a highlighted part needs 4 values but the size of the list is only 3, how to overcome this?

**Comment by MrShininnnnn** [comment]
@Manikanth06,
Please refer to this one - https://github.com/ShiningLab/POS-Tagger-for-Punctuation-Restoration/issues/2#issue-1008358735

**Comment by MrShininnnnn** [comment]
Closed as it is no longer active.
